spring:
  profiles:
    active: dev

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill??useUnicode=true&characterEncoding=utf8
    username: root
    password: root
